/*
DROP TABLE PERSON IF EXISTS;
CREATE MEMORY TABLE PERSON(
  P_USERNAME       VARCHAR(255) NOT NULL,
  P_FIRSTNAME      VARCHAR(255) NOT NULL,
  P_LASTNAME       VARCHAR(255) NOT NULL,
  P_ADDRESS        VARCHAR(255),
  P_CITY           VARCHAR(255),
  P_STATE          VARCHAR(255),
  P_ZIP            VARCHAR(5),
  P_PHONE          VARCHAR(11),
  P_DOB            DATE NOT NULL, -- DATE OF BIRTH
  PRIMARY KEY(P_USERNAME)
);

DROP TABLE VOLUNTEER IF EXISTS;
CREATE MEMORY TABLE VOLUNTEER(
  V_USERNAME       VARCHAR(255) NOT NULL,
  PRIMARY KEY (V_USERNAME),
  FOREIGN KEY (V_USERNAME) REFERENCES PERSON
);

DROP TABLE SCHOOL IF EXISTS;
CREATE MEMORY TABLE SCHOOL(
  SCH_ID          INTEGER NOT NULL,
  SCH_NAME        VARCHAR(255) NOT NULL,
  SCH_ADDRESS     VARCHAR(255) NOT NULL,
  SCH_CITY        VARCHAR(255) NOT NULL,
  SCH_STATE       VARCHAR(2) NOT NULL,
  SCH_ZIP         VARCHAR(5) NOT NULL,
  PRIMARY KEY (SCH_ID)
);

DROP TABLE STUDENT IF EXISTS;
CREATE MEMORY TABLE STUDENT(
  S_USERNAME       VARCHAR(255) NOT NULL,
  S_SCHOOL         INTEGER NOT NULL,
  S_MAJOR          VARCHAR(255) NOT NULL,
  S_GRADYEAR       INTEGER NOT NULL,
  S_ID             VARCHAR(255) NOT NULL,
  PRIMARY KEY (S_USERNAME),
  FOREIGN KEY (S_USERNAME) REFERENCES VOLUNTEER,
  FOREIGN KEY (S_SCHOOL) REFERENCES SCHOOL
);

DROP TABLE AVAILABLETIME IF EXISTS;
CREATE MEMORY TABLE AVAILABLETIME(
  AT_VOLUNTEER    VARCHAR(255) NOT NULL, -- USERNAME OF VOLUNTEER
  AT_STARTTIME    DATETIME NOT NULL,
  AT_ENDTIME      DATETIME NOT NULL,
  PRIMARY KEY (AT_VOLUNTEER, AT_STARTTIME, AT_ENDTIME),
  FOREIGN KEY (AT_VOLUNTEER) REFERENCES VOLUNTEER
);

DROP TABLE WORKER IF EXISTS;
CREATE MEMORY TABLE WORKER(
  W_USERNAME      VARCHAR(255) NOT NULL,
  W_POSITION      VARCHAR(255), -- POSITION IN BUSINESS (CEO, CFO, ETC.)
  PRIMARY KEY (W_USERNAME),
  FOREIGN KEY (W_USERNAME) REFERENCES PERSON
);

DROP TABLE LOGIN IF EXISTS;
CREATE MEMORY TABLE LOGIN(
  L_USERNAME      VARCHAR(255), -- USERNAME
  L_PASSWORD      VARCHAR(255), -- HASHED PASSWORD
  L_HASH          VARCHAR(255), -- HASH USED TO HASH PASSWORD
  PRIMARY KEY (L_USERNAME),
  FOREIGN KEY (L_USERNAME) REFERENCES PERSON
);

DROP TABLE ORGANIZATION IF EXISTS;
CREATE MEMORY TABLE ORGANIZATION(
  O_ID            INTEGER NOT NULL, -- UNIQUE ID
  O_NAME          VARCHAR(255) NOT NULL,
  O_DESCRIPTION   VARCHAR(255),
  O_ADDRESS       VARCHAR(255) NOT NULL,
  O_CITY          VARCHAR(255) NOT NULL,
  O_STATE         VARCHAR(2) NOT NULL,
  O_ZIP           VARCHAR(5) NOT NULL,
  O_ORGANIZER     VARCHAR(255) NOT NULL, -- USERNAME OF WORKER IN CHARGE
  PRIMARY KEY (O_ID),
  FOREIGN KEY (O_ORGANIZER) REFERENCES WORKER
);

DROP TABLE TAG IF EXISTS;
CREATE MEMORY TABLE TAG(
  T_NAME          VARCHAR(255) NOT NULL,
  PRIMARY KEY (T_NAME)
);

DROP TABLE ORGANIZATIONTAG IF EXISTS;
CREATE MEMORY TABLE ORGANIZATIONTAG(
  OT_ORGANIZATION INTEGER NOT NULL, -- ORGANIZATION ID
  OT_TAG          VARCHAR(255) NOT NULL, -- TAG
  PRIMARY KEY (OT_ORGANIZATION, OT_TAG),
  FOREIGN KEY (OT_TAG) REFERENCES TAG,
  FOREIGN KEY (OT_ORGANIZATION) REFERENCES ORGANIZATION
);

DROP TABLE EVENT IF EXISTS;
CREATE MEMORY TABLE EVENT(
  E_ID            INTEGER NOT NULL, -- EVENT ID
  E_DATETIME      DATETIME NOT NULL,
  E_NAME          VARCHAR(255) NOT NULL,
  E_DESCRIPTION   VARCHAR(255),
  E_ORGANIZATION  INTEGER NOT NULL, -- ID OF ORGANIZATION
  E_EMPLOYEEORG   VARCHAR(255), -- USERNAME OF SPECIFIC EMPLOYEE
  PRIMARY KEY (E_ID),
  FOREIGN KEY (E_ORGANIZATION) REFERENCES ORGANIZATION,
  FOREIGN KEY (E_EMPLOYEEORG) REFERENCES WORKER
);

DROP TABLE VOLUNTEEREVENT IF EXISTS;
CREATE MEMORY TABLE VOLUNTEEREVENT(
  VE_ID           INTEGER NOT NULL, -- UNIQUE ID
  VE_VOLUNTEER    VARCHAR(255) NOT NULL, -- VOLUNTEER
  VE_EVENT        INTEGER NOT NULL, -- EVENT ID
  VE_HOURS        INTEGER NOT NULL, -- HOURS VOLUNTEERED
  PRIMARY KEY (VE_ID),
  FOREIGN KEY (VE_VOLUNTEER) REFERENCES VOLUNTEER,
  FOREIGN KEY (VE_EVENT) REFERENCES EVENT
);



INSERT INTO PUBLIC.TAG(T_NAME) VALUES
  ('Advocacy'),
  ('Arts'),
  ('Cooperative Business'),
  ('Counseling'),
  ('Crisis Intervention'),
  ('Culture'),
  ('Disabilities'),
  ('Disaster Relief'),
  ('Domestic Violence'),
  ('Economic Justice'),
  ('Education'),
  ('Elderly'),
  ('Emergency Assistance'),
  ('Environment'),
  ('Financial Counseling'),
  ('Healthcare'),
  ('History'),
  ('Homelessness'),
  ('Housing'),
  ('Human Rights'),
  ('Immigration'),
  ('Literacy'),
  ('Mental Health'),
  ('Mentoring'),
  ('Nature'),
  ('Nutrition'),
  ('Poverty'),
  ('Recreation'),
  ('Senior Services'),
  ('Social Justice'),
  ('Substance Abuse'),
  ('Tutoring'),
  ('Veterans Issues'),
  ('Women''s issues'),
  ('Youth');

*/